title: "David Aulicino"
description: "Network & Infrastructure Engineer | Portfolio & Blog"
theme: jekyll-theme-slate
google_analytics:
show_downloads: false

# Menu di navigazione (apparir√† in alto)
header_pages:
 - index.md

# Impostazioni Markdown
markdown: kramdown
highlighter: rouge
