title: "David Aulicino"
description: "Network & Infrastructure Engineer | Portfolio & Blog"
theme: jekyll-theme-minimal
google_analytics:
show_downloads: false

# Menu di navigazione (opzionale, apparir√† in alto o a lato)
header_pages:
 - index.md

# Impostazioni Markdown
markdown: kramdown
highlighter: rouge